"""
build-data.py — Convert NWCB JSON data files to JS global-variable files.

Run from the website/ folder:
    python build-data.py

Reads JSON from ../data/ and writes JS files to ./data/
Each JS file assigns the JSON content to a global const variable,
so the browser can load it via <script> tags (works on file:// and https://).
"""

import json
import os
from datetime import datetime

# Where this script lives (website/)
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SOURCE_DIR = os.path.join(SCRIPT_DIR, "..", "data")
OUTPUT_DIR = os.path.join(SCRIPT_DIR, "data")

# Mapping: source JSON filename -> (output JS filename, JS variable name)
FILE_MAP = {
    "mounts.json":                  ("mounts.js",                  "MOUNTS_DATA"),
    "mount_combat_powers.json":     ("mount-combat-powers.js",     "MOUNT_COMBAT_POWERS_DATA"),
    "mount_equip_powers.json":      ("mount-equip-powers.js",      "MOUNT_EQUIP_POWERS_DATA"),
    "mount_insignia_bonuses.json":  ("mount-insignia-bonuses.js",  "MOUNT_INSIGNIA_BONUSES_DATA"),
    "mount_insignias.json":         ("mount-insignias.js",         None),  # Special: object with tierScaling + insignias
    "mount_collars.json":           ("mount-collars.js",           "MOUNT_COLLARS_DATA"),
    "companions.json":              ("companions.js",              "COMPANIONS_DATA"),
    "companion_powers.json":        ("companion-powers.js",        "COMPANION_POWERS_DATA"),
    "companion_enhancements.json":  ("companion-enhancements.js",  "COMPANION_ENHANCEMENTS_DATA"),
    "buffs.json":                   ("buffs.js",                   "BUFFS_DATA"),
    "artifacts.json":               ("artifacts.js",               "ARTIFACTS_DATA"),
    "classes.json":                 ("classes.js",                 "CLASSES_DATA"),
    "races.json":                   ("races.js",                   "RACES_DATA"),
}

def build_header(source_name):
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return (
        f"// Auto-generated by build-data.py on {ts}\n"
        f"// Source: ../data/{source_name}\n"
        f"// Do not edit — re-run build-data.py to regenerate.\n\n"
    )

def convert_file(source_name, output_name, var_name):
    source_path = os.path.join(SOURCE_DIR, source_name)
    output_path = os.path.join(OUTPUT_DIR, output_name)

    if not os.path.exists(source_path):
        print(f"  SKIP  {source_name} (not found)")
        return False

    with open(source_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    header = build_header(source_name)

    # Special handling for mount_insignias.json (object, not array)
    if var_name is None and source_name == "mount_insignias.json":
        tier_scaling = data.get("tierScaling", {})
        insignias = data.get("insignias", [])
        js_content = header
        js_content += f"const MOUNT_INSIGNIAS_TIER_SCALING = {json.dumps(tier_scaling, indent=2)};\n\n"
        js_content += f"const MOUNT_INSIGNIAS_DATA = {json.dumps(insignias, indent=2)};\n"
    else:
        js_content = header + f"const {var_name} = {json.dumps(data, indent=2)};\n"

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(js_content)

    print(f"  OK    {source_name} -> data/{output_name}")
    return True

def build_preview_data():
    """Scan images/preview/ and emit data/preview.js with discovered files.

    Layout:
        images/preview/gear/<Class>/*.{png,jpg,webp,...}
        images/preview/companions/*.{...}
        images/preview/mounts/*.{...}
        images/preview/other/*.{...}
    """
    preview_root = os.path.join(SCRIPT_DIR, "images", "preview")
    if not os.path.isdir(preview_root):
        print("  SKIP  preview (images/preview/ missing)")
        return False

    image_exts = {".png", ".jpg", ".jpeg", ".webp", ".gif"}
    classes = ["Barbarian", "Bard", "Cleric", "Fighter", "Paladin",
               "Ranger", "Rogue", "Warlock", "Wizard"]

    def list_images(rel_dir):
        abs_dir = os.path.join(preview_root, rel_dir)
        if not os.path.isdir(abs_dir):
            return []
        items = []
        for name in sorted(os.listdir(abs_dir)):
            if name.startswith("."):
                continue
            ext = os.path.splitext(name)[1].lower()
            if ext not in image_exts:
                continue
            # file path is relative to images/preview/ — preview.html prefixes "images/preview/"
            items.append({"file": rel_dir.replace(os.sep, "/") + "/" + name})
        return items

    def list_gear_for_class(cls):
        """Walk gear/<class>/. If it contains slot subfolders, walk one more level
        and tag each entry with its slot. If files are flat at the class level
        (no subfolders), return them without a slot tag (back-compat)."""
        class_dir = os.path.join(preview_root, "gear", cls)
        if not os.path.isdir(class_dir):
            return []
        # Detect slot subfolders (any subdirectory inside the class folder)
        subdirs = [
            d for d in sorted(os.listdir(class_dir))
            if not d.startswith(".") and os.path.isdir(os.path.join(class_dir, d))
        ]
        if subdirs:
            items = []
            for slot in subdirs:
                slot_items = list_images(os.path.join("gear", cls, slot))
                for it in slot_items:
                    it["slot"] = slot
                    items.append(it)
            # Also include any files dropped at the class root (untagged)
            root_items = list_images(os.path.join("gear", cls))
            return items + root_items
        # No subfolders → flat layout, no slot tags
        return list_images(os.path.join("gear", cls))

    gear = {cls: list_gear_for_class(cls) for cls in classes}
    companions = list_images("companions")
    mounts = list_images("mounts")
    other = list_images("other")

    payload = {"gear": gear, "companions": companions, "mounts": mounts, "other": other}

    output_path = os.path.join(OUTPUT_DIR, "preview.js")
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    js = (
        f"// Auto-generated by build-data.py on {ts}\n"
        f"// Source: images/preview/ (gear/<class>/, companions/, mounts/, other/)\n"
        f"// Drop image files into the matching folder, then re-run build-data.py.\n\n"
        f"window.PREVIEW_DATA = {json.dumps(payload, indent=2)};\n"
    )
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(js)

    total = sum(len(v) for v in gear.values()) + len(companions) + len(mounts) + len(other)
    print(f"  OK    images/preview/ -> data/preview.js ({total} images)")
    return True


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    print(f"Building JS data files...")
    print(f"  Source: {os.path.abspath(SOURCE_DIR)}")
    print(f"  Output: {os.path.abspath(OUTPUT_DIR)}")
    print()

    success = 0
    for source_name, (output_name, var_name) in FILE_MAP.items():
        if convert_file(source_name, output_name, var_name):
            success += 1

    if build_preview_data():
        success += 1

    total = len(FILE_MAP) + 1
    print(f"\nDone: {success}/{total} files converted.")

if __name__ == "__main__":
    main()
